version: "3.7"

services:
  app:
    build: .
    ports:
    - "8080:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tarak
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mbdb
    ports:
      - 5432:5432
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data
networks:
  s-network:
    driver: bridge
volumes:
  postgres-s-data:





